name: HMH Android PR Builder

on:
  pull_request:
    branches: [ develop, main ]

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Add Local Properties
        env:
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
          HMH_DEV_BASE_URL: ${{ secrets.HMH_DEV_BASE_URL }}
          HMH_PROD_BASE_URL: ${{ secrets.HMH_PROD_BASE_URL }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          echo kakaoApiKey=$KAKAO_API_KEY >> ./local.properties
          echo amplitudeApiKey=$AMPLITUDE_API_KEY >> ./local.properties
          echo keyAlias=$KEY_ALIAS >> ./local.properties
          echo keyPassword=$KEY_PASSWORD >> ./local.properties
          echo storePassword=$STORE_PASSWORD >> ./local.properties
          echo hmhDevBaseUrl=$HMH_DEV_BASE_URL >> ./local.properties
          echo hmhProdBaseUrl=$HMH_PROD_BASE_URL >> ./local.properties

      - name: Access Firebase Service
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Run Tests
        run: ./gradlew test

      - name: Verify Lint
        run: ./gradlew lint

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
