name: HMH Android Dependency Graph

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  generate-dependency-graph:
    name: Generate Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Generate Dependency Graph
        run: ./gradlew projectDependencyGraph

      - name: Commmit
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update dependency graph'

      - name: Push
        uses: ad-m/github-push-action@0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}